spring:
  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5433/edudb
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    initialization-mode: always

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/rootChangeLog.xml